project:
  type: website
  output-dir: docs

website:
  title: "Dilara's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      
    tools:
      - icon: github
        href: https://twitter.com
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://linkedin.com

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "You've found what you're looking for!" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: pulse 
      dark: superhero
    css: styles.css


editor: visual

