---
title: "About Me"
sidebar: false 
---

# Education

-   B.S., Industrial Engineering, Gazi University, Turkey, 2014 - 2019.
-   M.S., Industrial Engineering, Hacettepe University, Turkey, 2021 - 2023.
-   Ph.D., Industrial Engineering, Hacettepe University, Turkey, 2023 - ongoing.

# Work Experience

## Employements

1.  Hacettepe University, Research Assistant, 2020 - ongoing.

## Internships

1.  Lazzoni Furniture, Intern in Quality Department, August 2017

2.  Aselsan, Intern in Production Planning and Control Department, July 2018

3.  TAI, Candidate Industrial Engineer, November 2018 - May 2019

# Projects

1.  Studying on "Analysis of GHG Emissions: The case of Turkey". This study aims to describe the current status of greenhouse gas emissions in Turkey and to analyse sectoral data by applying a clustering algorithm.

2.  An FMEA study is currently underway for the improvement of service delivery for the facilities of a university's industrial engineering department.

3.  The paper "A Novel Method for Weighting Decision Makers for Failure Mode and Effect Analysis under Intuitionistic Fuzzy Environment" is under review at Quality and Reliability Engineering International.

# Competencies

R, Quarto, Git, Github, Python, Gurobi, Latex, Minitab

# Hobbies

I enjoy researching in my field, reading, traveling and dancing.

# Links

[CV](CV_Dilara%20Akkus__page-0001.jpg)

[Github](https://github.com/Dilara-pro)

[Linkedin](https://www.linkedin.com/in/dilara-akkus/)
